"""
Configuration for the zero-shot accident anticipation pipeline.

All filesystem locations are derived from environment variables (with sensible
local defaults), so the same code runs unchanged on different machines.

Environment variables
---------------------
    CLIPS_ROOT      Root directory for the Nexar 5s-clip dataset produced by
                    `process_5s_clips.py`.  Defaults to ``./data/nexar_clips_5s``
                    relative to this file.

Usage
-----
    # one-shot override
    export CLIPS_ROOT=/path/to/nexar/clips_5s
    python nexar_train.py
"""

import os

# ---- Dataset roots (overridable via environment variables) ----
_THIS_DIR = os.path.dirname(os.path.abspath(__file__))
CLIPS_ROOT = os.environ.get(
    "CLIPS_ROOT",
    os.path.join(_THIS_DIR, "data", "nexar_clips_5s"),
)

DATA_ROOT_TRAIN = os.path.join(CLIPS_ROOT, "training", "rgb_videos")
DATA_ROOT_TEST  = os.path.join(CLIPS_ROOT, "testing",  "rgb_videos")

# Auxiliary attention-map directories (kept for compatibility with the loader
# signature; in this work Nexar provides no per-frame attention so these dirs
# may be empty).
ATTN_ROOT_TRAIN = os.path.join(CLIPS_ROOT, "training", "attention_maps")
ATTN_ROOT_TEST  = os.path.join(CLIPS_ROOT, "testing",  "attention_maps")

# Annotation files generated by process_5s_clips.py
ANN_TRAIN = os.path.join(CLIPS_ROOT, "training.txt")
ANN_TEST  = os.path.join(CLIPS_ROOT, "testing.txt")

# Output directories (checkpoints + per-run logs)
OUTPUT_DIR  = os.path.join(CLIPS_ROOT, "output")
WEIGHTS_DIR = os.path.join(OUTPUT_DIR, "weights")
LOG_DIR     = os.path.join(OUTPUT_DIR, "logs")

# ---- Model parameters ----
MODEL_ID    = "OpenGVLab/VideoMAEv2-base"
EMBED_DIM   = 768
IMG_SIZE    = 224
FRAME_COUNT = 16        # Number of frames a single VideoMAE forward consumes
FPS         = 30        # Native FPS of every clip in clips_5s (target_fps=30)
SAMPLE_FPS  = 10        # Down-sampled FPS used during training (30 -> 10)

# Auxiliary branch parameters (kept for compatibility; the auxiliary branch is
# disabled at runtime in this work via the `--no_gcn` flag).
NUM_ROIS    = 12
ROI_SIZE    = 7
GCN_HIDDEN  = 256
GCN_DROPOUT = 0.1

# Fusion head hidden width
FUSION_DIM  = 512

# ---- Sliding window ----
WINDOW_SIZE   = 16
WINDOW_STRIDE = 4

# ---- Global mode ----
# A 5s clip @ 30fps becomes 50 frames after 30->10fps down-sampling
GLOBAL_NUM_FRAMES     = 50
GLOBAL_16F_NUM_FRAMES = 16

# ---- Training hyper-parameters ----
SEED                   = 42
TRAIN_BATCH_SIZE       = 3
VAL_BATCH_SIZE         = 3
NUM_WORKERS            = 4
LEARNING_RATE_BACKBONE = 1e-5
LEARNING_RATE_HEAD     = 1e-4
WEIGHT_DECAY           = 5e-4
EPOCHS                 = 20
ACCUMULATION_STEPS     = 8
TEMPERATURE            = 2.0
DROP_PATH_RATE         = 0.1

# Loss scale for the time-weighted CE (`ExpLoss`)
LOSS_SCALE = 5.0

# LR scheduler
SCHEDULER_TYPE       = "step"
SCHEDULER_STEP_EPOCH = 5
SCHEDULER_GAMMA      = 0.1
SCHEDULER_T_MAX      = 3
SCHEDULER_ETA_MIN    = 1e-6

# Backbone freezing strategy
FREEZE_BACKBONE_LAYERS = 0

# AMP
USE_AMP   = True
GRAD_CLIP = 5.0

# ---- Last-2s baseline (adapted from a previous 2nd-place solution) ----
LAST_NS                = 2.0
LAST_NS_NUM_FRAMES     = 16
LAST_NS_TEMPERATURE    = 2.0
LAST_NS_BALANCE        = True
LAST_NS_POS_THRESHOLD  = 1.5
LAST_NS_EPOCHS         = 10
LAST_NS_LR             = 1e-5
LAST_NS_SCHEDULER      = "cosine"
